#!/bin/sh
export JDBC_DRIVER_2="org.postgresql.Driver"
export JDBC_URL_2="jdbc:postgresql://172.31.31.11:5432/exec_module"
export POSTGRES_USERNAME_2="exec_module"
export POSTGRES_PASSWORD_2="exec_module1010#"
export WORKING_DIR_2="/home/execution-module/"
export TERRAFORM_POSTGRES_CONN_STR="postgres://exec_module1:exec_module1010@172.31.31.11:5432/exec_module?sslmode=disable"
export PULUMI_BASE_URL="https://rbac-pulumi.test.appmodz.net/"
export SES_ACCESS_KEY="AKIAQCCE4QSRF6ZQOTA4"
export SES_SECRET_KEY="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"
export SES_REGION="ap-south-1"
export SES_MAIL_SENDER="support@appmodernize.com"
export CHANGE_PASSWORD_LINK="https://rbac.test.appmodz.net/register/"
export FORGOT_PASSWORD_LINK="https://rbac.test.appmodz.net/forgot_password/"